export const PERM = {
  // Common
  DASHBOARD_VIEW: 'DASHBOARD.VIEW',

  // Leads
  LEADS_VIEW: 'LEADS.VIEW',
  LEADS_CREATE: 'LEADS.CREATE',
  LEADS_DUPLICATES_VIEW: 'LEADS.DUPLICATES.VIEW',
  LEADS_MERGE: 'LEADS.MERGE',

  // Leads workflow
  LEAD_REQUIREMENTS_VIEW: 'LEADS.REQUIREMENTS.VIEW',
  LEAD_HOSPITAL_REVIEWS_VIEW: 'LEADS.HOSPITAL_REVIEWS.VIEW',
  LEAD_QUOTATIONS_VIEW: 'LEADS.QUOTATIONS.VIEW',
  LEAD_VIL_VIEW: 'LEADS.VIL.VIEW',
  LEAD_ACTIVITIES_VIEW: 'LEADS.ACTIVITIES.VIEW',

  // Other modules
  HOSPITALS_VIEW: 'HOSPITALS.VIEW',
  TREATMENTS_VIEW: 'TREATMENTS.VIEW',

  // Admin-only
  MASTERS_VIEW: 'MASTERS.VIEW',
  USERS_VIEW: 'USERS.VIEW',
  REPORTS_VIEW: 'REPORTS.VIEW',
} as const;

export type PermissionCode = typeof PERM[keyof typeof PERM];